# Generated by Django 3.0.8 on 2021-01-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_purchase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
