# Generated by Django 3.0.8 on 2021-01-31 13:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210131_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, populate_from='title', unique=True),
        ),
    ]
