# Generated by Django 3.0.8 on 2021-02-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210131_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_measure',
            field=models.CharField(max_length=7, verbose_name='Единица измерения'),
        ),
    ]
